version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: controlyeshay-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - controlyeshay
    environment:
      - PHP_MEMORY_LIMIT=1G  # Aumentamos el límite de memoria a 1GB
      - PHP_MAX_EXECUTION_TIME=120
    mem_limit: 1G  # Límite de memoria a nivel de contenedor

  webserver:
    image: nginx:alpine
    container_name: controlyeshay-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - controlyeshay
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: controlyeshay-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - controlyeshay
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

networks:
  controlyeshay:
    driver: bridge

volumes:
  dbdata:
    driver: local
